export const routes = {
  home: "/",
  publicAuction: "/public-auction",
  publicAuctionItem: "/public-auction/:item",
  legalInformation: "/legal-information",
  legalInformationItem: "/legal-information/:item",
  faq: "/faq",
  event: "/event",
  events: "/events",
  eventId: "/event/:id",
  personal: "/personal",
  personalTab: "/personal/:tab",
  rate: "/rate",
  rates: "/rates",
  rateId: "/rate/:id",
  pawnshops: "/pawnshops",
  resetPasswordToken: "/reset-password/:token",
  page: "/page/:pageName",
  offer: "/page/offer",
  about: "/page/about",
  landing: "/landing",
};
